# Generated by Django 3.2.18 on 2023-04-07 17:50

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to=apps.post.models.post_img_path_generator)),
            ],
        ),
    ]
